// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { Autocomplete } from 'stimulus-autocomplete'
application.register('autocomplete', Autocomplete)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CharacteristicsFilterController from "./characteristics_filter_controller"
application.register("characteristics-filter", CharacteristicsFilterController)

import ChatSubscriptionController from "./chat_subscription_controller"
application.register("chat-subscription", ChatSubscriptionController)

import CloseModalController from "./close_modal_controller"
application.register("close-modal", CloseModalController)

import ConditionalUserFieldsController from "./conditional_user_fields_controller"
application.register("conditional-user-fields", ConditionalUserFieldsController)

import ConfirmAlertController from "./confirm_alert_controller"
application.register("confirm-alert", ConfirmAlertController)

import DisplayInfoWindowController from "./display_info_window_controller"
application.register("display-info-window", DisplayInfoWindowController)

import DropdownMenuController from "./dropdown_menu_controller"
application.register("dropdown-menu", DropdownMenuController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import MapController from "./map_controller"
application.register("map", MapController)

import MessageSubmitController from "./message_submit_controller"
application.register("message-submit", MessageSubmitController)

import SkipBookingDateValidationController from "./skip_booking_date_validation_controller"
application.register("skip-booking-date-validation", SkipBookingDateValidationController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import ValidateFormController from "./validate_form_controller"
application.register("validate-form", ValidateFormController)
