image:
  file: .gitpod/Dockerfile

ports:
  - name: Rails server
    port: 3000
    onOpen: open-preview
  - name: PostgreSQL server
    port: 5432
    onOpen: ignore

tasks:
  - name: Installing Dependencies
    init: |
      bundle install &&
      yarn install
      gp sync-done installs
      pip install yamllint
    openMode: split-left
  - name: create database & start server
    init: gp sync-await installs
    command: |
      rake db:create
      rake db:migrate
      rake db:seed
      rails server -b 0.0.0.0
    openMode: split-right

vscode:
  extensions:
    - Shopify.ruby-lsp

jetbrains:
  rubymine:
    prebuilds:
      version: both
