require:
  - standard
  - standard-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'out/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false
  NewCops: enable
  DisabledByDefault: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

# TODO: Reevaluate if these should or shouldn't be included.
# IMO they should be at least warning
Layout/LineLength:
  Severity: info

Metrics/BlockLength:
  Severity: info
  Exclude:
    - 'test/factories/*'

Metrics/MethodLength:
  Severity: info
  Exclude:
    - 'test/factories/*'

Metrics/AbcSize:
  Severity: info

Metrics/CyclomaticComplexity:
  Severity: info

Metrics/ClassLength:
  Severity: info
  Exclude:
    - 'test/**/*'

# TODO: This is temporary. We should change them to at least warning
Style/Documentation:
  Severity: info
