extends: default

ignore:
  - config/locales/*.yml
  - vendor/**/*
  - db/**/*
  - bin/*
  - out/*
  - test/fixtures/**/* # fixtures don't have proper yml syntax, as they use ERB

rules:
  line-length:
    max: 120

  document-start:
    present: false

  truthy:
    check-keys: false

  comments:
    min-spaces-from-content: 1
