openapi: 3.0.0
info:
  version: 1.0.0
  title: Quouch API
  description: Meet Quouch

servers:
  - url: 'http://localhost:3000/api/v1'
    description: Development server

paths:
  /login:
    $ref: './paths/login.yaml'

  /users:
    $ref: './paths/users.yaml'

  /users/{id}:
    $ref: 'paths/user_id.yaml'

  /bookings:
    $ref: 'paths/bookings.yaml'

  /couches:
    $ref: 'paths/couches.yaml'

  /messages:
    $ref: 'paths/messages.yaml'

  /notifications:
    $ref: 'paths/notifications.yaml'

  /plans:
    $ref: 'paths/plans.yaml'

  /chats:
    $ref: 'paths/chats.yaml'

  /characteristics:
    $ref: 'paths/characteristics.yaml'

  /couch_facilities:
    $ref: 'paths/couch_facilities.yaml'

  /logout:
    $ref: 'paths/logout.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
