# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run system tests - desktop and mobile
name: 'System Tests'

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pull-requests: write

env:
  RAILS_ENV: test
  CI: true
  DATABASE_URL: 'postgres://rails:password@localhost:5432/quouch_development'
  BASE_USER_EMAIL: 'test@quouch.com'
  BASE_USER_PASSWORD: 'password' # Change for a random secret!

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  desktop:
    runs-on: ubuntu-latest
    permissions: write-all
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: quouch_development
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:drop
          bin/rails db:create
          bin/rails db:migrate

      - name: Run desktop tests
        run: bin/rails system:desktop
        env:
          RAILS_MASTER_KEY: ${{ secrets.MASTER_KEY }}

  mobile:
    runs-on: ubuntu-latest
    permissions: write-all
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: quouch_development
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:drop
          bin/rails db:create
          bin/rails db:migrate

      - name: Run mobile tests (iPhone)
        run: bin/rails system:ios
        env:
          RAILS_MASTER_KEY: ${{ secrets.MASTER_KEY }}
